### ISSUE TITLE
Binson light can not correctly parse an array of objects

### ISSUE THREAD

**Issue by AndreasHansson73** [assaabloy-ppi/binson-c-light#10]
If we have an array of objects, such as this

```
{ "a":
    [
        {"d":false},
        {"e":true}, // This object is not parsed
        9223372036854775807
    ]
}
```

The second array object is not found, in fact, no array items after the first object is considered to be part of the array.

Please see this patch to binson_light_test.c that add a testcase that failes. When the parser is fixed, the test should succeed.
In the diff you can also see two lines of code that are commented out that looks like this
`//p->state = 0x02;`

If I un-comment these lines everything works, this may be a hint of what the problem is. 
I think that what happens is that the parser state is BINSON_PARSER_STATE_BEFORE_ARRAY_VALUE before parsing the object in the array. But when we call binson_parser_go_upto_object, we do not return to that state so the parser do not know that we are in an array, hence the next call to binson_parser_next_array_value will fail.

```
diff --git a/binson_light_test.c b/binson_light_test.c
index 1269641..bcd76e6 100644
--- a/binson_light_test.c
+++ b/binson_light_test.c
@@ -296,6 +296,56 @@ int8_t test_parser_lenfuzz( binson_parser *p )
   return -1;
 }
 
+int8_t test_parser_array1(binson_parser *p)
+{
+  // {"a":[{"d":false},{"e":true},9223372036854775807]}
+  const uint8_t b1[]  =
+    "\x40\x14\x01\x61"
+        "\x42"
+           "\x40"
+                "\x14\x01\x64\x45"
+            "\x41"
+            "\x40"
+                "\x14\x01\x65\x44"
+            "\x41"
+            "\x13\xff\xff\xff\xff\xff\xff\xff\x7f"
+       "\x43"
+    "\x41";
+
+  int64_t fff = 0;
+
+  binson_parser_init(p, (uint8_t*)&b1, sizeof(b1));
+  binson_parser_reset( p );
+  binson_parser_field( p, "a" );
+  binson_parser_go_into_array( p );
+
+  assert(binson_parser_next_array_value( p ));
+
+  binson_parser_go_into_object( p );
+  binson_parser_field( p, "d" );
+  assert(binson_parser_get_boolean(p) == false);
+  binson_parser_go_upto_object( p );
+
+  //p->state = 0x02;
+  assert(binson_parser_next_array_value( p ));
+  binson_parser_go_into_object( p );
+
+  binson_parser_field( p, "e" );
+  assert(binson_parser_get_boolean(p) == true);
+  binson_parser_go_upto_object( p );
+
+  //p->state = 0x02;
+  assert(binson_parser_next_array_value( p ));
+
+  fff = binson_parser_get_integer( p );
+  assert(fff == 9223372036854775807);
+
+  binson_parser_go_upto_array( p );
+
+  return -1;
+}
+
+
 
 /*=====================*/
 int main(void)
@@ -320,6 +370,7 @@ int main(void)
  putchar('\n');
  putchar('7'); UT_RUN( test_parser_basic( &p ) );
  putchar('8'); UT_RUN( test_parser_lenfuzz( &p ) );
+ putchar('9'); UT_RUN( test_parser_array1( &p ) );
   
  putchar('\n'); putchar('\n');

```

**Comment by SylwBar** [comment]
I think I found this problem in April, I wrote it about it.
Here is summary of what I investigated then:
Do you think it is the same problem?

...
Playing with QuickCheck model I found some problems with parser.

My brief analysis shows that mixed-multi level binson structures aren’t handled properly. I mean situation when there is array inside object which is inside array etc…

Minimal error vector proposed by QuickCheck is:
#{"A" => {array,[]}}
This is Erlang term describing binson object with one field “A” of value that is empty array.
Or in other bytes:
uint8_t test1[] = "\x40\x14\x01\x41\x42\x43\x41";

The problem is with functions binson_parser_go_upto_object|array.
Both of them assume that after leaving lower-level object upper level object is the same type – array or object.
They are hardcoded to return BINSON_PARSER_STATE_BEFORE_FIELD or BINSON_PARSER_STATE_BEFORE_ARRAY_VALUE which I believe is wrong.
After some attempts to solve this problem I think that there is some sort of stack required to handle type of items: objects or arrays.
This is not trivial fix so I don’t want to introduce it without discussion. After all – I could be wrong too.

**Comment by AndreasHansson73** [comment]
It looks like you have encountered the same issue as I have. I thinks you are poin-pointing the problem. I have not thought about a solution myself but I agree that this is not a trivial fix. A fix also requires a lot of testing since it will affect the core of the parser.

**Comment by SylwBar** [comment]
Great that we came to the same conclusion.
Regarding testing. 
I prepared QuickCheck model for extensive testing of binson-c-light.
https://github.com/assaabloy-ppi/binson-erlang
The idea of QC is to create a model of behaviour of tested object and automatic generation of test-cases (thousands/millions depending on time). This way I found the bug we are discussing.
After creating solution for problem we could re-run QC to check.

**Comment by AndreasHansson73** [comment]
Sounds good. It would be really great if we could enable automatic testing on commit in this project. That would be really helpful.

**Comment by SylwBar** [comment]
It is possible to run QuickCheck model automatically using QuickCheck Continuous Integration server:
http://quickcheck-ci.com/. This server is provided by QuviQ - company which stands beside QC.
So far I'm running Erlang QuickCheck manually on my desktop. With QC CI it is possible to do it automatically.
What is required - tested project must be open-sourced on github, but instead QC CI server runs on commercial version of QuickCheck which has great support for testing C code (e.g. no need to write stubs).

**Comment by AndreasHansson73** [comment]
I don't know if it's possible to use QuickCheck on github but it seems that for opensource projects the travis ci environments can be used.

**Comment by SylwBar** [comment]
Hi. I've checked - we could use Travis CI for running free version of Erlang QuickCheck (QC mini) or QC CI server. QC CI could be connected to open-sources github projects.
Advantage of using dedicated QC CI server is that there is commercial version of QuickCheck installed, which has number of advantages over free version.

QC model for testing binson-c-light is based on free version of QC so it can be triggered from both Travis CI or QC CI.
However, commercial version of QC is much better: enables state-full testing. With full version we could test much better.
Anyway, back to original problem: I could re-test proposed fix using my desktop PC, I could show how to run QC model for binson-c-light too.

**Comment by ppmag** [comment]
Hi all,
and thanks a lot for detailed issue investigations, 
also I'm sorry for a long story with this issue.

Finally I finished with v2 redesigned version, where I took into account 
your above suggestions.

For now this issue is claimed fixed.
See: binson_light_test.c -> test_parser_14()  for proof.

PS: original test code was patched by me to meet new API requirements (no implicit block enter actions inside the parser from now).
